// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class TapTapRevolutionResources
{
        public const string achievement_the_150_in_15 = "CgkInsD9g8YHEAIQAw"; // <GPGSID>
        public const string achievement_you_are_60_awesome = "CgkInsD9g8YHEAIQDw"; // <GPGSID>
        public const string leaderboard_30_seconds = "CgkInsD9g8YHEAIQEQ"; // <GPGSID>
        public const string achievement_the_800_in_60 = "CgkInsD9g8YHEAIQDg"; // <GPGSID>
        public const string achievement_the_600_in_60 = "CgkInsD9g8YHEAIQDQ"; // <GPGSID>
        public const string leaderboard_unlimited_mode = "CgkInsD9g8YHEAIQEw"; // <GPGSID>
        public const string achievement_the_400_in_30 = "CgkInsD9g8YHEAIQCQ"; // <GPGSID>
        public const string achievement_the_300_in_30 = "CgkInsD9g8YHEAIQCA"; // <GPGSID>
        public const string achievement_the_200_in_30 = "CgkInsD9g8YHEAIQBw"; // <GPGSID>
        public const string achievement_the_100_in_30 = "CgkInsD9g8YHEAIQBg"; // <GPGSID>
        public const string achievement_you_are_30_awesome = "CgkInsD9g8YHEAIQCg"; // <GPGSID>
        public const string achievement_the_400_in_60 = "CgkInsD9g8YHEAIQDA"; // <GPGSID>
        public const string achievement_you_are_15__awesome = "CgkInsD9g8YHEAIQBQ"; // <GPGSID>
        public const string leaderboard_60_seconds = "CgkInsD9g8YHEAIQEg"; // <GPGSID>
        public const string leaderboard_15_seconds = "CgkInsD9g8YHEAIQEA"; // <GPGSID>
        public const string achievement_the_200_in_15 = "CgkInsD9g8YHEAIQBA"; // <GPGSID>
        public const string achievement_the_100_in_15 = "CgkInsD9g8YHEAIQAg"; // <GPGSID>
        public const string achievement_the_200_in_60 = "CgkInsD9g8YHEAIQCw"; // <GPGSID>
        public const string achievement_the_50_in_15 = "CgkInsD9g8YHEAIQAQ"; // <GPGSID>

}

