// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class TapTapRevolutionResources
{
        public const string achievement_the_150_in_15 = "CgkIpKLJn74EEAIQCg"; // <GPGSID>
        public const string achievement_you_are_60_awesome = "CgkIpKLJn74EEAIQHA"; // <GPGSID>
        public const string leaderboard_new_15_seconds = "CgkIpKLJn74EEAIQFw"; // <GPGSID>
        public const string leaderboard_30_seconds = "CgkIpKLJn74EEAIQEw"; // <GPGSID>
        public const string achievement_login = "CgkIpKLJn74EEAIQAA"; // <GPGSID>
        public const string achievement_the_600_in_60 = "CgkIpKLJn74EEAIQGg"; // <GPGSID>
        public const string achievement_the_400_in_30 = "CgkIpKLJn74EEAIQEA"; // <GPGSID>
        public const string achievement_the_300_in_30 = "CgkIpKLJn74EEAIQDw"; // <GPGSID>
        public const string achievement_the_200_in_30 = "CgkIpKLJn74EEAIQDg"; // <GPGSID>
        public const string achievement_the_100_in_30 = "CgkIpKLJn74EEAIQDQ"; // <GPGSID>
        public const string achievement_you_are_30_awesome = "CgkIpKLJn74EEAIQEg"; // <GPGSID>
        public const string achievement_the_400_in_60 = "CgkIpKLJn74EEAIQGQ"; // <GPGSID>
        public const string achievement_the_800_in_60 = "CgkIpKLJn74EEAIQGw"; // <GPGSID>
        public const string achievement_you_are_15__awesome = "CgkIpKLJn74EEAIQEQ"; // <GPGSID>
        public const string leaderboard_60_seconds = "CgkIpKLJn74EEAIQFA"; // <GPGSID>
        public const string leaderboard_unlimited_mode = "CgkIpKLJn74EEAIQFQ"; // <GPGSID>
        public const string achievement_the_200_in_15 = "CgkIpKLJn74EEAIQDA"; // <GPGSID>
        public const string achievement_the_100_in_15 = "CgkIpKLJn74EEAIQHQ"; // <GPGSID>
        public const string achievement_the_200_in_60 = "CgkIpKLJn74EEAIQGA"; // <GPGSID>
        public const string achievement_the_50_in_15 = "CgkIpKLJn74EEAIQCw"; // <GPGSID>

}

